name: Node.js CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn
    - run: git config --global user.email "actions@codysherman.com"
    - run: git config --global user.name "GitHub Actions"
    - run: ./deploy.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}
    - run: >-
           curl -L -X POST -w '%{http_code}\n'
           -H "Content-Type: application/json"
           -H "Authorization: token ${{ secrets.DEPLOY_KEY }}"
           "https://api.github.com/repos/${{ github.repository }}/pages/builds"
           | tail -1 | grep 201
